services:
  video_processor_worker:
    build:
      context: ./bin
      dockerfile: Dockerfile
    container_name: video_processor_worker
    volumes:
      - ../:/app
    env_file:
      - ${WORKER_ENV_FILE:-.env}
    command: ["python", "worker.py"]
    networks:
      - video-upload-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  video-upload-network:
    external: true
    name: video-upload-network
